collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      page_class: "member"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      page_class: "post"
  - scope:
      path: ""
    values:
      layout: "default"
